name: Publish Gem 
description: Publish gem to GPR
inputs:
  package-glob:
    description: "File glob to match the .gem files to push"
    default: "pkg/*.gem"

runs:
  using: "composite"
  steps:
    - name: Package Gem
      shell: bash
      run: bundle exec rake build

    - name: Push Gem 
      shell: bash
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.github_token }}"
        OWNER: ${{ github.repository_owner }}
        PACKAGE_GLOB: ${{ inputs.package-glob }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} $PACKAGE_GLOB
