name: Publish Gem 
description: Publish gem to GPR
inputs:
  package-glob:
    description: "File glob to match the .gem files to push"
    default: "pkg/*.gem"
  token:
    description: "Token to access the GitHub package registry. Normally using secrets.github_token is enough."
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Gem
      shell: bash
      run: bundle exec rake build

    - name: Setup GPR
      shell: bash
      env:
        GEM_HOST_API_KEY: "Bearer ${{ inputs.token }}"
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials

    - name: Push Gem
      shell: bash
      env:
        OWNER: ${{ github.repository_owner }}
        PACKAGE_GLOB: ${{ inputs.package-glob }}
      run: |
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} $PACKAGE_GLOB
