name: Publish Gem
description: Publish gem to GPR
inputs:
  package-glob:
    description: "File glob to match the .gem files to push"
    default: "pkg/*.gem"

runs:
  using: "composite"
  steps:
    - name: Push Gem
      shell: bash
      env:
        # Expects GEM_HOST and GEM_HOST_API_KEY to be set
        GEM_GLOB: ${{ inputs.package-glob }}
      run: |
        if ! gem push --host "$GEM_HOST" $GEM_GLOB | tee push.out; then
          gemerr=$?
          if grep "has already been pushed" push.out; then
            echo Gem Already Pushed
            exit 0
          fi
          echo ::error::Gem Push Failed
          cat push.out | sed 's/^/::error::/'
          exit $gemerr
        fi
        if ! gem tag --push --verbose; then
          echo ::warning::Failed to tag pushed commit
        fi
        exit 0
