name: Bats
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.3.0

    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1 # .ruby-version
      with:
        bundler-cache: true # bundle install

    - name: Test
      env:
        GITHUB_PAT: ${{ secrets.github_token }}
      run: bats -r --report-formatter junit test.bats/
