name: Bats
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1.2.0
      with:
        bats-version: 1.3.0

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        bundler-cache: true # bundle install

    - name: Test
      env:
        GITHUB_PAT: ${{ secrets.github_token }}
      run: bats -r --report-formatter junit test.bats/
