name: Gem Build and Release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Install the bundle and run the gems test suite.
  test:
    name: Gem / Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1 # .ruby-version for ruby setup
      with:
        bundler-cache: true # bundle install and cache

    - name: Test
      env:
        GITHUB_PAT: ${{ secrets.github_token }}
      run: bundle exec rake

  # Builds on the main branch, that pass testing above, will trigger a push of a
  # new gem version. If the version.rb has not been bumped since the last
  # release, this will be a no-op, other wise the new version will be added to
  # the registry: https://github.com/orgs/fac/packages?ecosystem=rubygems
  release:
    name: Gem / Release
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: fac/ruby-gem-setup-github-packages-action@devp/v2
      with:
        token: ${{ secrets.github_token }}

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Build Gem
      run: bundle exec rake build

    # Release production gem version from default branch
    - name: Push Release Gem
      if:   github.ref == 'refs/heads/main'
      uses: fac/ruby-gem-push-action@devp/v2

    # PR branch builds will release pre-release gems
    - name: Push Pre-Release Gem
      if:   github.ref != 'refs/heads/main'
      uses: fac/ruby-gem-push-action@devp/v2
      with:
        release: false
        pre-release: true
