name: Gem Build and Release
on: push

jobs:
  # Install the bundle and run the gems test suite.
  test:
    name: RubyGems / Test
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.github_token }}

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1 # .ruby-version for ruby setup
      with:
        bundler-cache: true # bundle install and cache

    - name: Test
      run: bundle exec rake

  # Builds on the main branch, that pass testing above, will trigger a push of a
  # new gem version. If the version.rb has not been bumped since the last
  # release, this will be a no-op, other wise the new version will be added to
  # the registry.
  # https://github.com/orgs/fac/packages?ecosystem=rubygems
  release:
    name: RubyGems / Release
    needs: test
    #if:    github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1 # .ruby-version
      with:
        bundler-cache: true # bundle install and cache

    - name: Build Gem
      shell: bash
      run: bundle exec rake build

    - name: Setup GPR
      uses: fac/rubygems-setup-gpr-action@devp/v1.0.0
      with:
        token: ${{ secrets.github_token }}

    - name: Push Gem
      uses: ./.github/actions/rubygems-push-action
